dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
dotenv: .env
networks:
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
